### ISSUE TITLE
TypeError: fs_1.rmSync is not a function

### ISSUE THREAD

**Issue by VAggrippino** [return-0x0/node-clear-npx-cache#1]
It doesn't work:
```
❯ npx clear-npx-cache
Need to install the following packages:
  clear-npx-cache
Ok to proceed? (y) y
/home/vince/.npm/_npx/066c52483104548d/node_modules/clear-npx-cache/lib/index.js:22
            fs_1.rmSync(subdirectory, { recursive: true });
                 ^

TypeError: fs_1.rmSync is not a function
    at clearCache (/home/vince/.npm/_npx/066c52483104548d/node_modules/clear-npx-cache/lib/index.js:22:18)
    at Object.<anonymous> (/home/vince/.npm/_npx/066c52483104548d/node_modules/clear-npx-cache/bin/clear-npx-cache.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

❯ node --version
v10.19.0

❯ npm --version
7.20.0
```

That's the _system_ version of node on my version of Ubuntu. I tried with a newer version of node after reading somewhere that it's only supported by "new versions" of node. I kinda wish that comment was more specific, but clear-npx-cache works if I use 14.17.3.

I appreciate the idea of the tool and it confirms a suspicion I had after reading/hearing from several sources that `npx` does not install the packages you use it to run. I even posted nodejs/nodejs.dev#1592 on the official documentation repo.

Why not just use `rm -rf $(npm config get cache)/_npx` instead of using a tool?

**Comment by retueZe** [comment]
1. I'm not using Linux
2. This is JS, not BASH. It can be integrated, for example, in the gulpfile.js
